language: python
branches:
  only:
    - master
python:
  - "3.6"
install:
  - pip install tensorflow
  - pip install .
  - pip install pytest
  - pip install pytest-cov
  - pip install codecov
  - pip install twine
script:
  - pytest --cov=morpheus
after_success:
  - codecov
  - python travis_deploy.py
env:
  global:
    secure: 3Jsp9ouJC4CrPZ3g8/9cCpuNUGgK6lR3mAl/WKowdXOHRmA2MslNvOKoW9a64GZxOgySMcJEIJH0EfctbRu3ryvujnw1ZMkZjGBNVwtskduQalQhUo2kknlbNBqJ8zfPR66NwKW++eZNXt0gOsyezZCvIB29MFhFa+7NooHh+j8LdOUVLWgnUy86T8M/Q66qc1j2o3sA00H7PN1N/bX9C1NU2CPXcm04piv44uLNLYbnxuoiTbPfFx0G1L16/g842M1uPTu8ZLWQMUTQCl7WpkmwzS+HapnW/B+uZ9LjaUs611LpznjnuaFdyoGdpcdw1ZqUbKMt0Yi1YMLYPCIRWoWMv06ZxJdHt+APT4RXzx8OwF/Kj3gG6sJYxvFN1AUZurgeGyCaxRkfmi4VHgpuPC1PG/JEP7P7CAa2GsVMo9JlqISEnm58Cqh+uFM++K06C3l1PmB2fcQkIW2PN0ijxcW51XoDpzPBg3lOXr0BLfIH8xCmP9eQgHvTo8pjBewkfsHYVc+oSgngixmopOWcmtHlbuGSX0z2xpOcE6rw8R/TjIOsGuw0CCUqvuajvOxc9kivI7jCDVvo4wM1rDWL/Ri0W35DSYkuMSvspsvkiWtAxdQ8P9iCBQ77hrHhGe1t1jfx+nHkewDYZcpf+wFendgbDD6pDmmKUkj9akpDrPE=
