language: python
branches:
  only:
    - master
python:
  - "3.6"
install:
  - pip install tensorflow
  - pip install .
  - pip install pytest
  - pip install pytest-cov
  - pip install codecov
  - pip install twine
script:
  - pytest --cov=morpheus
after_success:
  - codecov
  - python travis_deploy.py
env:
  global:
    secure: QgXloY6mKEqCBRu680CCnSz+2a4vmyv7v3PQTiUniaJ3sxXzbTvfIniOK0+8IULYxu3NCNDrXtkdbAQvBygn953DHvkg8UXnrMt7usLr8b4wJLtDhvxYAVYLffSeovle7Q5z2zmVQCu6wqN1S8bKvHk9S4z+s/BtYm3zZ/SzgnOy6ZXPjBZsrhmUbq5JQ29SsR/xeZtU4c+4dnyswHIkIk6QqRuMO43aYfw/ZUiRiEja93Z4++FtNfmzNcJjhWJtEO4I9HyJ+5Hp67wx0sdE9KKYMtF3KngDdpF0fTFY65bgFDBUZCg/zVNqBe2gUS0kXvsLZUlnbMnaz1FrbqmvWM2XUcJ9Ldlm5P9jK6Fl1A03oFybPAa9jfjk2FRLKRo0MbZ/TKECYEd9cfm1fpUeiQ4A046MGCIBsUfmOO5Nfp5qnMAI5Or74Of8ymNMo2OwkPAJEe0vOuIYFmXbhoooJ4BxWlddTzsGxhBN0+1sX5CDCtIqJalcyy2iFZRKjWT4XF1ZU8d3FX895y18x3x0Sty0d24GhUAFSfTLNIdIm2XqN4D1yBC1RJ2PDUx+gqXRUGuDyzjbVIucM1NkAE8JEhDk33neSR1SZvQT4iOA2x6Rw6mOmym32mdz0vsGEaLnTBmx0bOm0PYFYcZovUDaPfaQoKy6c9GX5dh9qHBoXJo=
