language: python
python:
  - "3.6"
install:
  - pip install .
  - pip install pytest
  - pip install pytest-cov
  - pip install --user codecov
script:
  - pytest --cov=morpheus
after_success:
  - codecov