language: python
services:
  - docker
branches:
  only:
    - master
python:
  - "3.6"
install:
  - pip install tensorflow
  - pip install .
  - pip install pytest
  - pip install pytest-cov
  - pip install codecov
  - pip install twine
script:
  - pytest --cov=morpheus
after_success:
  - codecov
  - python travis_deploy.py
env:
  global:
    secure: NYABjItsRsEvzXDAlkGClhqTjZWVLVm+DNnlnlZ1ngGqSS53MOcY+Sqa73RjhiNPSaidxWOZngb8NP6+FKgyPuHR14abRNdU3FxNuiqHvNSv9wpUKO8gsqd5/9Yy9OjO/VXcw0gtr2D58w4bTCOqDkEIVxq31dY2qrcXMyEMqi4rYS+xAVa6u4NvJDEh8M3P6WgEh50/9v99CJlykV7FgkFT9EY3tEAiO9laATpz7dC1A4byJjZI0BiSYKiIlBSMTH/CQZRfxiHyyEbMQYAW7kSsFagge2XOYhQJ9I2RtpeQGPUzcrKcUH/XZitOPXT3WuwVIkGwhdHiDVyhLDhZWXdNT6F2pVswq50Amc0cyEc2/SuSkZsKrIFIal9pm8LAhc3dD2hMDRo5moYWt1XiXcGfiERw9mQXtb6uZd5EYguqs1PpEhY26wFnDQHat3yZ2d05LhWCCL/mLn2AhT9M9lXZYGvpPY3crkL2ai24UJWc6/Vl3bmqRLyvja7K3qa+hPjeQ9ZbhjYJNZ4Yz1etkKbkmU+ZPqSArkT+Xq/Znlfa+2QpB3p8V99od8Ql9N6brkglj1dD//Zi1cQ7fGGJoQt5WCibxA9lcruTjaxtd2Dv8msaeN+6L00av11Fq4Srvln56f6QHHl9AzUFLF0/y1NA+tZmP67/m/UnNS2J0pU=
